FROM python:3.12-slim

WORKDIR /app

RUN apt-get update && apt-get install -y \
    libgl1 \
    libglib2.0-0 \
    libsm6 \
    libxext6 \
    libxrender1 \
    libxcb1 \
    && rm -rf /var/lib/apt/lists/*

# CPU-only PyTorch
RUN pip install --no-cache-dir \
    torch==2.5.1 \
    torchvision==0.20.1 \
    --index-url https://download.pytorch.org/whl/cpu    

COPY requirements_api.txt .

RUN pip install --no-cache-dir -r requirements_api.txt

COPY src ./src

COPY api ./api

COPY outputs/yolo/Rail_Defect_Detect_7class/weights/best.pt ./models/best.pt

ENV API_DEVICE=cpu

ENV MODEL_PATH=/app/models/best.pt

EXPOSE 8000

CMD ["uvicorn", "api.main:app", "--host", "0.0.0.0", "--port", "8000"]

