FROM python:3.12-slim

WORKDIR /app

COPY requirements_streamlit.txt .

RUN pip install --no-cache-dir -r requirements_streamlit.txt

COPY streamlit ./streamlit

EXPOSE  8501

CMD [ "streamlit", "run", "streamlit/app.py", "--server.address==0.0.0.0", "--server.port=8501"]