stages:

  train:
    cmd: python -m src.train
    deps:
      - src/train.py
      - src/config.py
      - data.yaml
      - data
    outs:
      - outputs/yolo/rail_Defect_Detect/weights/best.pt

  evaluate:
    cmd: python -m src.evaluate
    deps:
      - src/evaluate.py
      - src/config.py
      - data.yaml
      - outputs/yolo/rail_Defect_Detect/weights/best.pt
    metrics:
      - outputs/frontend_data/test_metrics.json: 
          cache: false

  frontend_data:
    cmd: python -m src.frontend_data
    deps:
      - src/frontend_data.py
      - src/inference.py
      - src/config.py
      - outputs/yolo/rail_Defect_Detect/weights/best.pt
      - data/test  
    outs:
      - outputs/frontend_data/images

  