stages:

  train:
    cmd: python -m src.train
    deps:
      - src/train.py
      - src/config.py
      - data_7class.yaml
      - data_7class
    outs:
      - outputs/yolo/Rail_Defect_Detect_7class/weights/best.pt

  evaluate:
    cmd: python -m src.evaluate
    deps:
      - src/evaluate.py
      - src/config.py
      - data_7class.yaml
      - outputs/yolo/Rail_Defect_Detect_7class/weights/best.pt
    metrics:
      - outputs/frontend_data/test_metrics.json: 
          cache: false

  frontend_data:
    cmd: python -m src.frontend_data
    deps:
      - src/frontend_data.py
      - src/inference.py
      - src/config.py
      - outputs/yolo/Rail_Defect_Detect_7class/weights/best.pt
      - data_7class/test/images  
    outs:
      - outputs/frontend_data/images

  