artifact_location: file:c:/Users/Kun Bi/Desktop/rail_yolo_object_identification/notebook/runs/mlflow/848556703972460844
creation_time: 1790619064061
experiment_id: '848556703972460844'
last_update_time: 1790619064061
lifecycle_stage: active
name: c:\Users\Kun Bi\Desktop\rail_yolo_object_identification\outputs\yolo
