artifact_uri: file:c:/Users/Kun Bi/Desktop/rail_yolo_object_identification/notebook/runs/mlflow/848556703972460844/226d186eabea42838eaf0c551880ad62/artifacts
end_time: null
entry_point_name: ''
experiment_id: '848556703972460844'
lifecycle_stage: active
run_id: 226d186eabea42838eaf0c551880ad62
run_name: Rail_Defect_Detect-2
source_name: ''
source_type: 4
source_version: ''
start_time: 1790619064367
status: 1
tags: []
user_id: Kun Bi
